<?php

namespace panix\mod\shop\api\controllers;

use panix\mod\user\models\forms\LoginForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\ContentNegotiator;
use yii\filters\RateLimiter;
use yii\helpers\ArrayHelper;
use yii\rest\ActiveController;
use yii\rest\Serializer;
use yii\web\Response;

/**
 * Class CountryController
 * @package panix\mod\shop\api\v1\controllers
 */
class CountryController extends ActiveController
{
    public $modelClass = 'panix\mod\shop\api\models\Country';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        \Yii::$app->user->enableSession = false;
    }

    public $serializer = [
        'class' => Serializer::class,
        'collectionEnvelope' => 'items',
    ];

    public function actionNew()
    {

//Yii::$app->response->format = Response::FORMAT_JSON;
        $requestParams = Yii::$app->getRequest()->getBodyParams();
        if (empty($requestParams)) {
            $requestParams = Yii::$app->getRequest()->getQueryParams();
        }

        /* @var $modelClass \yii\db\BaseActiveRecord */
        $modelClass = $this->modelClass;

        $query = $modelClass::find();
        if (!empty($filter)) {
            $query->andWhere($filter);
        }

        return Yii::createObject([
            'class' => ActiveDataProvider::class,
            'query' => $query,
            'pagination' => [
                'params' => $requestParams,
            ],
            'sort' => [
                'params' => $requestParams,
            ],
        ]);
    }

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'contentNegotiator' => [
                'class' => ContentNegotiator::class,
                'formatParam' => 'format',
                'formats' => [
                    'json' => Response::FORMAT_JSON,
                    'xml' => Response::FORMAT_XML,
                ]
            ],
            'rateLimiter' => [
                'class' => RateLimiter::class
            ],
            'corsFilter' => [
                'class' => \yii\filters\Cors::class,
            ],
            'authenticatior' => [
                'class' => QueryParamAuth::class, // Implementing access token authentication
                'except' => ['login', 'new'], /// There is no need to validate the access token method. Note the distinction between $noAclLogin
            ]
        ]);
    }


    public function actionLogin()
    {
        $model = new LoginForm();
        if ($model->load(Yii::$app->getRequest()->getBodyParams(), '') && $model->login()) {
            return [
                'access_token' => $model->login(),
            ];
        } else {
            return $model->getFirstErrors();
        }
    }
}


