<?php

namespace panix\mod\shop\models;

use panix\mod\user\models\User;
use Yii;
use panix\engine\db\ActiveRecord;


/**
 * Class SearchResult
 * @property integer $id
 * @property integer $user_id
 * @property integer $result
 * @property string $query
 */
class SearchResult extends ActiveRecord
{

    const MODULE_ID = 'shop';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%shop__search_result}}';
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(),[
            'ip_create'=>Yii::t('app/default','IP')
        ]);
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert)
            $this->created_at = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
